"""Enable login for the public service's database role (run by `migrate`).

The role `graintime_public` (created by migration 0006) may only SELECT the
public_site_status table. Its password is generated by `init` into the
public-secrets volume, the only secret the public container can see.
Safe to run on every start.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from sqlalchemy import text

from .db import get_engine
from .logging import get_logger, setup_logging

PUBLIC_SECRETS_DIR = Path(os.environ.get("GRAINTIME_PUBLIC_SECRETS_DIR", "/run/graintime-public-secrets"))
PUBLIC_PASSWORD_FILE = "public_db_password"


def enable(password: str) -> None:
    with get_engine().begin() as c:
        # Literal quoting via quote_literal: ALTER ROLE takes no bind parameters.
        quoted = c.execute(text("SELECT quote_literal(:p)"), {"p": password}).scalar_one()
        c.execute(text(f"ALTER ROLE graintime_public WITH LOGIN CONNECTION LIMIT 10 PASSWORD {quoted}"))


def main() -> int:
    setup_logging("migrate")
    log = get_logger("public_role")
    path = PUBLIC_SECRETS_DIR / PUBLIC_PASSWORD_FILE
    if not path.exists():
        log.info("public role password not found; public service login left disabled")
        return 0
    enable(path.read_text(encoding="utf-8").strip())
    log.info("public role login enabled")
    return 0


if __name__ == "__main__":
    sys.exit(main())
